### ISSUE TITLE
Reduce COCOFactory memory footprint

### ISSUE THREAD

**Issue by fmpaezri** [jccaicedo/localization-agent#11]
Refactor COCOFactory so that memory footprint is reduced and execution time is not penalized

**Comment by fmpaezri** [comment]
Try to use data streams or something like providers

**Comment by fmpaezri** [comment]
The size of the annotations is huge

**Comment by fmpaezri** [comment]
This might help with the parallel experimentation

**Comment by jccaicedo** [comment]
We also hope the memory footprint to decrease when the objects of interest (at least 200px in one dimension) are selected. Agree that when parallel simulations are run, we still want to be memory efficient, but not sure if that's another issue.

**Comment by fmpaezri** [comment]
Using all annotations requires ~2GB in memory, but these are not duplicated by the process Pool or so it seems, the top command shows 1.5 GB per process but the available memory seems to remain the same as before the process launch. So in fact only one Factory instance is created in the parent process. Closing the issue
