### ISSUE TITLE
Image pixels normalization

### ISSUE THREAD

**Issue by jccaicedo** [jccaicedo/localization-agent#28]
Controller.py line 25:

If the image is forwarded to a Caffe network, and this networks is set to subtract the mean image, we do not need to normalize the raw pixels. It's useful only in the case of gray scale images.

**Comment by jccaicedo** [comment]
I just indented the line to make it dependent on the gray-scales condition. Please close this issue if you think the solution is OK.

**Comment by fmpaezri** [comment]
That was what I planned doing, but I wonder if it is also necessary to normalize the feature values before passing them to the recurrent part? I think I checked min and max values for an example activation and they were like 0 and 13 respectively. But I was not very rigorous and my memory might trick me.

**Comment by fmpaezri** [comment]
Check literature for other preprocessing proposals of pretrained features

**Comment by jccaicedo** [comment]
I think the original RCNN paper did not apply any sophisticated feature normalization, and that one is a very influential paper that uses pretrained features. Here is the link to the paper:
http://arxiv.org/abs/1311.2524

And here is the link to the code that the author released, which kind of says it's not a big deal:
https://github.com/rbgirshick/rcnn/blob/master/rcnn_scale_features.m

Also, in my RL work, I did not remember having applied some sort of normalization either. I would say we are fine using raw feature maps as input, and keep an eye both, experimental results and the literature to identify best practices.

**Comment by jccaicedo** [comment]
I think we can use CNN feature maps without normalization for now. Closing this issue.
