### ISSUE TITLE
Add offline generation of sequences to replay memory

### ISSUE THREAD

**Issue by fmpaezri** [jccaicedo/localization-agent#30]

**Comment by jccaicedo** [comment]
The main idea is to generate about 1 or 2 GB of videos to initialize training. But, do you really think this is a necessary optimization? I'd like to move on with experiments before trying to over-optimize what we already have. I'd say this is low priority.

**Comment by jccaicedo** [comment]
The replay memory does not seem to be a useful feature when training large scale models. Closing this issue for now.
